### PR TITLE
chore: fix incorrect path in README.md

### PR DESCRIPTION
**Pull request by sellskin**

### CODE REVIEW

**Review by lidangzzz — APPROVED** [review]

**Comment by lidangzzz** [comment]
Thanks for your pull request.

Also please leave your eth address here so that we can airdrop some tokens to you.

Thanks!

**Comment by curtis0815** [comment]
0x6E2FF642d60d1c99811F0a1A39e1b0250C488Cce

Best Regards,
Curtis

**Comment by sellskin** [comment]
> 0x6E2FF642d60d1c99811F0a1A39e1b0250C488Cce Best Regards, Curtis
> […](#)
> On Apr 13, 2024 at 12:20 +0800, 立党 Lidang ***@***.***>, wrote: Merged #113 into main. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

Who are you?? Are you joking

**Comment by sellskin** [comment]
> Thanks for your pull request.
> 
> Also please leave your eth address here so that we can airdrop some tokens to you.
> 
> Thanks!

Thank you very much, please ignore the comments upstairs, it may be malicious

My ETH wallet address： 0x62F70A36AA049d965521b2528186EC799aBd80Ed

**Comment by ash2410** [comment]
0xe14c9d04F49A2dB144868fbab91370aA6DD986d6   thank you











在 2024-04-13 14:00:55，"sellskin" ***@***.***> 写道：

Thanks for your pull request.

Also please leave your eth address here so that we can airdrop some tokens to you.

Thanks!

Thank you very much, please ignore the comments upstairs, it may be malicious

My ETH wallet address： 0x62F70A36AA049d965521b2528186EC799aBd80Ed

**Comment by 18153203306** [comment]
0xD0c2D54A2cB700243d466129aC9b4E2A517bB214
---- Replied Message ----
***@***.*** ***@***.***>Date04/13/2024 14:56 ***@***.***> ***@***.***>SubjectRe: [Project-DARC/DARC] chore: fix incorrect path in README.md (PR #113)
0xe14c9d04F49A2dB144868fbab91370aA6DD986d6 thank you
在 2024-04-13 14:00:55，"sellskin" ***@***.***> 写道：
Thanks for your pull request.
Also please leave your eth address here so that we can airdrop some tokens to you.
Thanks!
Thank you very much, please ignore the comments upstairs, it may be malicious
My ETH wallet address： 0x62F70A36AA049d965521b2528186EC799aBd80Ed

**Comment by fengeail** [comment]
0x079de221797a6995b98E9E148ADF53322743221E




峰
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Project-DARC/DARC"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月13日(星期六) 中午12:20
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [Project-DARC/DARC] chore: fix incorrect path in README.md (PR #113)





 
Thanks for your pull request.
 
Also please leave your eth address here so that we can airdrop some tokens to you.
 
Thanks!

**Comment by LeeeMak** [comment]
0xe127E45C3BB2585904a631AAEDe5db1A9F81d41D
感谢信立党大大伟大的项目

**Pull request merged**
